name: games

services:
  db:
    image: mariadb:11.3.2
    container_name: games-db
    environment:
      MARIADB_DATABASE: $MYSQL_DATABASE
      MARIADB_USER: $MYSQL_USER
      MARIADB_PASSWORD: $MYSQL_PASSWORD
      MARIADB_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3307:3306"
#    volumes:
#    - ./mariadb_data:/var/lib/mysql
